#!/bin/bash
set -e

tag=`docker container run --rm --entrypoint "" zenika/alpine-firestore-backup gcloud version --format=value'("Google Cloud SDK")'`
echo $tag        
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
docker tag $IMAGE_NAME ${repoName}:${tag}
docker push ${repoName}:${tag}

echo "$GCLOUD_SERVICE_KEY" | base64 -d > 'key.json'
docker version
#cat key.json | docker login -u _json_key --password-stdin https://gcr.io/zenika-hub
#Docker client is a old one: 17.06 and --password-stdin doesn't work.
docker login -u _json_key -p "$(cat key.json)" https://gcr.io/zenika-hub 
for published_tag in "latest" $tag; do
    docker tag $IMAGE_NAME gcr.io/zenika-hub/alpine-firestore-backup:${published_tag}
    docker push gcr.io/zenika-hub/alpine-firestore-backup:${published_tag}
    for region in "us" "eu" "asia"; do
        #publish in the different regions
        docker login -u _json_key -p "$(cat key.json)" https://$region.gcr.io/zenika-hub 
        docker tag gcr.io/zenika-hub/alpine-firestore-backup:${published_tag} $region.gcr.io/zenika-hub/alpine-firestore-backup:${published_tag}
        docker push $region.gcr.io/zenika-hub/alpine-firestore-backup:${published_tag}
    done
done
