#!/bin/bash
set -e

tag=`docker container run --rm --entrypoint "" zenika/alpine-firestore-backup gcloud version --format=value'("Google Cloud SDK")'`
echo $tag        
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
docker tag $IMAGE_NAME ${repoName}:${tag}
docker push ${repoName}:${tag}

echo "$GCLOUD_SERVICE_KEY" | base64 -d > 'key.json'
docker version
#cat key.json | docker login -u _json_key --password-stdin https://gcr.io/zenika-hub
#Docker client is a old one: 17.06 and --password-stdin doesn't work.
docker login -u _json_key -p "$(cat key.json)" https://gcr.io/zenika-hub 
docker tag $IMAGE_NAME gcr.io/zenika-hub/alpine-firestore-backup:latest
docker push gcr.io/zenika-hub/alpine-firestore-backup:latest
docker tag $IMAGE_NAME gcr.io/zenika-hub/alpine-firestore-backup:${tag}
docker push gcr.io/zenika-hub/alpine-firestore-backup:${tag}
